#!/bin/sh

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

mkdir -p ~/.config/tmux
ln -s $(pwd)/tmux.conf ~/.config/tmux/
ln -s $(pwd)/tmux-cht-command ~/.config/tmux/
ln -s $(pwd)/tmux-cht-languages ~/.config/tmux/

# Install plugins
~/.tmux/plugins/tpm/bin/install_plugins
